require("titus.plugins-setup")
require("titus.core.options")
require("titus.core.keymaps")
require("titus.core.colorscheme")
require("titus.plugins.comment")
require("titus.plugins.nvim-tree")
require("titus.plugins.lualine")
require("titus.plugins.telescope")
require("titus.plugins.nvim-cmp") -- base for autocompletion
require("titus.plugins.lsp.mason")
require("titus.plugins.lsp.lspsaga")
require("titus.plugins.lsp.lspconfig")
require("titus.plugins.autopairs")
require("titus.plugins.treesitter")
require("titus.plugins.gitsigns")
require("titus.plugins.presence")
require("titus.plugins.bufferline")
require("titus.plugins.colorizer")
